# -*- coding: utf-8 -*-
"""file-sorter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOQGPPm7g08RmNWM3U1uHjgFYTsLchk0
"""

pip install pandas

import pandas as pd

reference_df = pd.read_csv('reference.csv')
unsorted_df = pd.read_csv('unsorted2.csv', encoding='latin-1')

reference_df['CYS_code'] = reference_df['CYS'].str[:3]  # Extract first 3 letters of CYS; ignore numbers
cys_college_mapping = dict(zip(reference_df['CYS_code'], reference_df['COLLEGE']))

unsorted_df['COLLEGE'] = unsorted_df['CYS'].str[:3].map(cys_college_mapping)

prog_funding_mapping = dict(zip(reference_df['PROG'], reference_df['TYPE OF FUNDING']))
prog_scholarship_mapping = dict(zip(reference_df['PROG'], reference_df['TYPE OF SCHOLARSHIP']))

unsorted_df['TYPE OF FUNDING'] = unsorted_df['PROG'].map(prog_funding_mapping)
unsorted_df['TYPE OF SCHOLARSHIP'] = unsorted_df['PROG'].map(prog_scholarship_mapping)

unsorted_df.to_csv('updated_unsorted.csv', index=False)

# Read the updated_unsorted.csv file
updated_df = pd.read_csv('updated_unsorted.csv')

# Sort the DataFrame
sorted_df = updated_df.sort_values(by=['COLLEGE', 'PROG', 'NAME OF STUDENT'], ascending=True)

# Save the sorted DataFrame to a new file
sorted_df.to_csv('sorted_output.csv', index=False)